### ISSUE TITLE
Field 'id' cannot be empty

### ISSUE THREAD

**Issue by Bo-UT** [nextflow-io/nf-prov#38]
Hi
I am new to nextflow. I ran `sarek-3.4.4` for `mutect2` on the server. Our server is offline. I downloaded nf-prov@1.2.2 from https://github.com/nextflow-io/nf-prov/releases/download/1.2.2/nf-prov-1.2.2.zip, and moved it to ~/.nextflow/plugins. I constantly got the error 
```
Nov-16 12:32:26.791 [main] ERROR nextflow.cli.Launcher - @unknown
org.pf4j.InvalidPluginDescriptorException: Field 'id' cannot be empty
```

The log file is 
<details><summary> Error log </summary>
Nov-16 12:32:26.424 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins declared=[nf-validation@1.1.3, nf-prov@1.2.2]
Nov-16 12:32:26.425 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Nov-16 12:32:26.425 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[nf-validation@1.1.3, nf-prov@1.2.2]
Nov-16 12:32:26.429 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-validation version: 1.1.3
Nov-16 12:32:26.454 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-validation@1.1.3' resolved
Nov-16 12:32:26.455 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-validation@1.1.3'
Nov-16 12:32:26.775 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-validation@1.1.3
Nov-16 12:32:26.775 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-prov version: 1.2.2
Nov-16 12:32:26.791 [main] ERROR nextflow.cli.Launcher - @unknown
org.pf4j.InvalidPluginDescriptorException: Field 'id' cannot be empty
	at org.pf4j.AbstractPluginManager.validatePluginDescriptor(AbstractPluginManager.java:989)
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:895)
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:139)
	at nextflow.plugin.CustomPluginManager.loadPluginFromPath(CustomPluginManager.groovy:46)
	at nextflow.plugin.LocalPluginManager.loadPluginFromPath(LocalPluginManager.groovy:98)
	at nextflow.plugin.PluginUpdater.load0(PluginUpdater.groovy:342)
	at nextflow.plugin.PluginUpdater.installPlugin(PluginUpdater.groovy:198)
	at nextflow.plugin.PluginUpdater.prepareAndStart(PluginUpdater.groovy:145)
	at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:335)
	at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:340)
	at nextflow.plugin.PluginsFacade.load(PluginsFacade.groovy:239)
	at nextflow.plugin.Plugins.load(Plugins.groovy:52)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:342)
	at nextflow.cli.Launcher.run(Launcher.groovy:503)
	at nextflow.cli.Launcher.main(Launcher.groovy:658)
</details>

The code I used to run nextflow
```
nextflow run $WORKFLOW \
--genome null --igenomes_ignore --fasta $REF_FASTA \
-profile singularity \
--save_output_as_bam \
-c $CONFIG \
--tools mutect2 \
--input $SAMPLE_SHEET \
--outdir $GATK_RESULT
```

Thanks for your help!

**Comment by Bo-UT** [comment]
I add the plugins setting in the `.config` file, but that doesn't help. The `nextflow` version I am using is `24.10.0`. 
```
plugins {
  id 'nf-prov@1..2.2'
}
```
